POST http://localhost:8081/api/orders HTTP/1.1
content-type: application/json

{
  "user_id":"batee5",
  "items": [{"id":"id5","quantity":2,"price":500, "merchantId": 1},{"id":"id","quantity":1,"price":2000, "merchantId": 2}]
}

